#!/usr/bin/env bash

STARTUP_TIME=40
PROJECT_LOAD_TIME=6

#exit if no sound card is specified
if [ -z "$1" ]; then
    echo usage: $0 external/internal probe
    exit 1
fi

#load necessary kernel modules for midi
if ! grep -q snd_virmidi /proc/modules; then 
    echo load snd_virmidi
    sudo modprobe snd-virmidi midi_devs=3
fi
if ! grep -q snd_seq_midi /proc/modules; then 
    echo snd_seq_midi
    sudo modprobe snd_seq_midi
fi

#start jack
echo start qjackctl
nohup qjackctl -p "$1" >/dev/null 2>&1 &

#start bitwig
echo start bitwig-studio
nohup bitwig-studio "$2" >/dev/null 2>&1 &

if ! [ -z "$3" ]; then
    echo waiting for bitwig to open completely before opening more projects
    sleep $STARTUP_TIME
fi

for project in "${@:3}"
do
    sleep $PROJECT_LOAD_TIME
    echo load project "$project"
    bitwig-studio "$project"
done
