#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [[ "$1" == "start" ]]
then
    ps -ef | grep connection-daemon | awk '{print $2}' | xargs kill -9 >/dev/null 2>&1
    nohup $DIR/connection-daemon $DIR/config > $DIR/log 2>&1 &
    echo connection-daemon started
fi
if [[ "$1" == "stop" ]]
then
    ps -ef | grep connection-daemon | awk '{print $2}' | xargs kill -9 >/dev/null 2>&1
    echo connection-daemon stopped
fi
